module.exports = {
    nodes: [
        {
            identifier: "main",
            host: "lavalinklnwza.herokuapp.com",
            port: 443,
            password: "reirin",
            secure: true,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {                                                               //with ssl
            identifier: "ssl_1",
            host: "usui-linku.kadantte.moe",
            port: 443,
            password: "Usui#0256",
            secure: true,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "ssl_2",
            host: "node1.kartadharta.xyz",
            port: 443,
            password: "kdlavalink",
            secure: true,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "ssl_3",
            host: "lavalink.oops.wtf",
            port: 443,
            password: "www.freelavalink.ga",
            secure: true,
            retryAmount: Infinity,
            retryDelay: 3000,
        }, 
        {                                                               //without ssl
            identifier: "without_ssl_1",
            host: "lavalink.islantay.tk",
            port: 8880,
            password: "waifufufufu",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_2",
            host: "uk1.buckytm.com",
            port: 28112,
            password: "f82263yh75f6r5",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_3",
            host: "lavalink.gaproknetwork.xyz",
            port: 2333,
            password: "gaproklavalink",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_4",
            host: "node2.lavalink.chiquicalris.me",
            port: 2392,
            password: "lavalink_is_cool",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_5",
            host: "node3.lavalink.chiquicalris.me",
            port: 2393,
            password: "lavalink_is_cool",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_6",
            host: "node4.lavalink.chiquicalris.me",
            port: 2394,
            password: "lavalink_is_cool",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_7",
            host: "lavalink.chiquicalris.me",
            port: 2330,
            password: "lavalink_is_cool",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_8",
            host: "weez-node.cf",
            port: 2333,
            password: "FreeLava",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_9",
            host: "lavalink.oops.wtf",
            port: 2000,
            password: "www.freelavalink.ga",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_10",
            host: "lavalink.darrenofficial.com",
            port: 80,
            password: "anything as a password",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_11",
            host: "usa.lavalink.mitask.tech",
            port: 2333,
            password: "lvserver",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_12",
            host: "lavalink.houseofgamers.xyz",
            port: 2333,
            password: "lavalink",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_13",
            host: "node.annnekkk.com",
            port: 2333,
            password: "youshallnotpass",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
        {
            identifier: "without_ssl_14",
            host: "lava.link",
            port: 80,
            password: "youshallnotpass",
            secure: false,
            retryAmount: Infinity,
            retryDelay: 3000,
        },
    ],
}
